// <auto-generated />
using System;
using GEMSRegistration.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GEMSRegistration.Migrations
{
    [DbContext(typeof(GEMSRegistrationContext))]
    [Migration("20200505222125_INITIAL")]
    partial class INITIAL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GEMSRegistration.Models.Attendee", b =>
                {
                    b.Property<int>("AttendeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LocationID");

                    b.Property<int>("Quantity");

                    b.Property<int?>("WorkshopID");

                    b.HasKey("AttendeeID");

                    b.HasIndex("LocationID");

                    b.HasIndex("WorkshopID");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("GEMSRegistration.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocationName");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GEMSRegistration.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasMaxLength(11);

                    b.HasKey("ID");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("GEMSRegistration.Models.Workshop", b =>
                {
                    b.Property<int>("WorkshopID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FacilitatorID");

                    b.Property<int?>("ParticipantID");

                    b.Property<string>("WorkshopDescription")
                        .IsRequired();

                    b.Property<string>("WorkshopName")
                        .IsRequired();

                    b.HasKey("WorkshopID");

                    b.HasIndex("FacilitatorID");

                    b.HasIndex("ParticipantID");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("GEMSRegistration.Models.Facilitator", b =>
                {
                    b.HasBaseType("GEMSRegistration.Models.Person");

                    b.Property<string>("Affiliation");

                    b.HasDiscriminator().HasValue("Facilitator");
                });

            modelBuilder.Entity("GEMSRegistration.Models.Participant", b =>
                {
                    b.HasBaseType("GEMSRegistration.Models.Person");

                    b.Property<int>("Age");

                    b.Property<string>("ContactFName")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("ContactLName")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<DateTime>("RegistrationDate");

                    b.HasDiscriminator().HasValue("Participant");
                });

            modelBuilder.Entity("GEMSRegistration.Models.Attendee", b =>
                {
                    b.HasOne("GEMSRegistration.Models.Location", "Location")
                        .WithMany("Attendees")
                        .HasForeignKey("LocationID");

                    b.HasOne("GEMSRegistration.Models.Workshop", "Workshop")
                        .WithMany("Attendees")
                        .HasForeignKey("WorkshopID");
                });

            modelBuilder.Entity("GEMSRegistration.Models.Workshop", b =>
                {
                    b.HasOne("GEMSRegistration.Models.Facilitator", "Facilitator")
                        .WithMany("Workshops")
                        .HasForeignKey("FacilitatorID");

                    b.HasOne("GEMSRegistration.Models.Participant", "Participant")
                        .WithMany("Workshops")
                        .HasForeignKey("ParticipantID");
                });
#pragma warning restore 612, 618
        }
    }
}
